- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.config/nvim:
        create: true
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.zprofile:
    ~/.zshrc:

- shell:
    - git submodule update --init --recursive
